Du_an_2mail/Du_an_2/Du_an_2/Areas/Admin/Controllers/Nha_cung_capController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data2;
using Data2.Models.DataModel;

namespace Du_an_2.Areas.Admin.Controllers
{
    public class Nha_cung_capController : Controller
    {
        private Management db = new Management();

        // GET: Admin/Nha_cung_cap
        public ActionResult Index()
        {
            return View(db.nha_Cung_Caps.ToList());
        }

        // GET: Admin/Nha_cung_cap/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nha_cung_cap nha_cung_cap = db.nha_Cung_Caps.Find(id);
            if (nha_cung_cap == null)
            {
                return HttpNotFound();
            }
            return View(nha_cung_cap);
        }

        // GET: Admin/Nha_cung_cap/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Nha_cung_cap/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma_nha_cung_cap,Ten_nha_cung_cap,So_dien_thoai,Email,Dia_chi,Trang_thai_1")] Nha_cung_cap nha_cung_cap)
        {
            if (ModelState.IsValid)
            {
                db.nha_Cung_Caps.Add(nha_cung_cap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nha_cung_cap);
        }

        // GET: Admin/Nha_cung_cap/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nha_cung_cap nha_cung_cap = db.nha_Cung_Caps.Find(id);
            if (nha_cung_cap == null)
            {
                return HttpNotFound();
            }
            return View(nha_cung_cap);
        }

        // POST: Admin/Nha_cung_cap/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma_nha_cung_cap,Ten_nha_cung_cap,So_dien_thoai,Email,Dia_chi,Trang_thai_1")] Nha_cung_cap nha_cung_cap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nha_cung_cap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nha_cung_cap);
        }

        // GET: Admin/Nha_cung_cap/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nha_cung_cap nha_cung_cap = db.nha_Cung_Caps.Find(id);
            if (nha_cung_cap == null)
            {
                return HttpNotFound();
            }
            return View(nha_cung_cap);
        }

        // POST: Admin/Nha_cung_cap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nha_cung_cap nha_cung_cap = db.nha_Cung_Caps.Find(id);
            db.nha_Cung_Caps.Remove(nha_cung_cap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Du_an_2mail/Du_an_2/Du_an_2/Controllers/Nha_cung_capController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data2;
using Data2.Models.DataModel;
using PagedList;

namespace Du_an_2.Controllers
{
    public class Nha_cung_capController : Controller
    {
        // GET: Nha_cung_cap
        Management db = new Management();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Nha_cung_capPartial()
        {
            var ncc = db.nha_Cung_Caps.Where(x => x.Trang_thai_1 == true).ToList();
            return PartialView(ncc);
        }
        public ViewResult San_pham_ncc(int? id, int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            Nha_cung_cap ncc = db.nha_Cung_Caps.SingleOrDefault(x => x.Ma_nha_cung_cap == id);
            if (ncc == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<San_pham> sp = db.San_Phams.Where(x => x.Ma_nha_cung_cap == id && x.Trang_thai_1==true).ToList();
            return View(sp.ToPagedList(pageNumber, pageSize));

        }
      
    }
}

Du_an_2mail/Du_an_2/Du_an_2/Controllers/San_phamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data2;
using Data2.Models.DataModel;
using PagedList;

namespace Du_an_2.Controllers
{
    public class San_phamController : Controller
    {
        Management db = new Management();
        // GET: San_pham_moiPartial
        public PartialViewResult San_pham_moiPratial()
        {

           // var san_pham = db.San_Phams.Take(6).ToList();
            //var san_pham = from sp in db.San_Phams.Take(4)
            //             orderby sp.Ma_san_pham descending
            //             select sp;                           

            return PartialView(db.San_Phams.Take(4).OrderByDescending(x=>x.Ma_san_pham).ToList());

        }
        public PartialViewResult San_phamPartial(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            var san_pham = db.San_Phams.Include(a=>a.Danh_muc).Include(b=>b.Nha_Cung_Cap).Where( x =>x.Trang_thai_1==true && x.Nha_Cung_Cap.Trang_thai_1== true && x.Danh_muc.Trang_thai_1==true).ToList();
            return PartialView(san_pham.ToPagedList(pageNumber, pageSize));
        }
        public PartialViewResult Trai_cayPartial()
        {
            var trai_cay = db.San_Phams.Where(x => x.Ma_danh_muc == 1).ToList();
            return PartialView(trai_cay);
        }
        public PartialViewResult Nuoc_epPartial()
        {
            var nuoc_ep = db.San_Phams.Where(x => x.Ma_danh_muc == 2).ToList();
            return PartialView(nuoc_ep);
        }
        public ViewResult Chi_tiet_san_pham( int id)
        {
           // var sp = db.San_Phams.Include(x => x.Danh_muc);
            var sp = db.San_Phams.Include(x => x.Danh_muc).Include(x=>x.Nha_Cung_Cap).SingleOrDefault(x => x.Ma_san_pham == id);
            if (sp != null)
            {
                return View(sp);
            }
            else
            {
                // trả về trang 404
                Response.StatusCode = 404;
                return null;
            }
        }
      
    }
}

Du_an_2mail/Du_an_2/Du_an_2/Views/Nha_cung_cap/Nha_cung_capPartial.cshtml
@using Data2.Models.DataModel
@model List<Nha_cung_cap>
@{
    foreach (var item in Model)
    {
        <li class="has-image">
            
            <a href="@Url.Action("San_pham_ncc","Nha_cung_cap", new {@id= +item.Ma_nha_cung_cap })" title="Vegetables">@item.Ten_nha_cung_cap</a>
        </li>
    }
}

Du_an_2mail/Du_an_2/Du_an_2/Views/Nha_cung_cap/San_pham_ncc.cshtml
@using PagedList.Mvc;
@using PagedList;
@using Data2.Models.DataModel;
@model PagedList.PagedList<San_pham>
@{
    ViewBag.Title = "San_pham_ncc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="center-column" class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
    <div class="product-category-page">
        <!-- Nav Bar -->
        <div class="products-bar">
            <div class="row">
                <div class="col-md-6 col-xs-6">
                    <div class="gridlist-toggle" role="tablist">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#products-grid" data-toggle="tab" aria-expanded="true"><i class="fa fa-th-large"></i></a></li>
                            <li><a href="#products-list" data-toggle="tab" aria-expanded="false"><i class="fa fa-bars"></i></a></li>
                        </ul>
                    </div>

                    <div class="total-products">There are 12 products</div>
                </div>

                <div class="col-md-6 col-xs-6">
                    <div class="filter-bar">
                        <form action="#" class="pull-right">
                            <div class="select">
                                <select class="form-control">
                                    <option value="">Sort By</option>
                                    <option value="1">Price: Lowest first</option>
                                    <option value="2">Price: Highest first</option>
                                    <option value="3">Product Name: A to Z</option>
                                    <option value="4">Product Name: Z to A</option>
                                    <option value="5">In stock</option>
                                </select>
                            </div>
                        </form>
                        <form action="#" class="pull-right">
                            <div class="select">
                                <select class="form-control">
                                    <option value="">Relevance</option>
                                    <option value="1">Price: Lowest first</option>
                                    <option value="2">Price: Highest first</option>
                                    <option value="3">Product Name: A to Z</option>
                                    <option value="4">Product Name: Z to A</option>
                                    <option value="5">In stock</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-content">
            <!-- Products Grid -->
            <div class="tab-pane active" id="products-grid">
                <div class="products-block">
                    <div class="row">
                        @{
                            foreach (var item in Model)
                            {
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="product-item">
                                        <div class="product-image">

                                            <img class="img-responsive" src="@item.Anh_san_pham" alt="Product Image">

                                        </div>

                                        <div class="product-title">
                                            <a href="@Url.Action("Chi_tiet_san_pham","San_pham", new {@id= +item.Ma_san_pham })">
                                                @item.Ten_san_pham
                                            </a>
                                        </div>

                                        <div class="product-rating">
                                            <div class="star on"></div>
                                            <div class="star on"></div>
                                            <div class="star on "></div>
                                            <div class="star on"></div>
                                            <div class="star"></div>
                                        </div>

                                        <div class="product-price">
                                            <span class="sale-price">đ @item.Gia_km<sup>đ</sup></span>
                                            <span class="base-price">đ @item.Gia<sup>đ</sup></span>
                                        </div>

                                        <div class="product-buttons">
                                            <a class="add-to-cart" href="#">
                                                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                                            </a>

                                            <a class="add-wishlist" href="#">
                                                <i class="fa fa-heart" aria-hidden="true"></i>
                                            </a>

                                            <a class="quickview" href="@Url.Action("Chi_tiet_san_pham","San_pham", new {@id= +item.Ma_san_pham })">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                        }


                    </div>
                </div>
            </div>



        </div>

        <!-- Pagination Bar -->
        <div class="pagination-bar">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="text"> Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount</div>
                </div>

                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="pagination">
                        <ul class="page-list">
                            <li>@Html.PagedListPager(Model, page => Url.Action("San_pham_ncc", new { page }))</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>